[package]
name = "dataflow-expression"
version = "0.1.0"
publish = false
authors = ["ReadySet Technology, Inc. <info@readyset.io>"]
edition = "2021"

[dependencies]
chrono = { version = "0.4.0", features = ["serde"] }
chrono-tz = { version = "0.8.6", features = ["serde"] }
serde = { version = "1.0.8", features = ["derive"] }
serde_json = { version = "1.0" }
rust_decimal = { version = "1.26" }
lazy_static = "1.4.0"
regex = "1.4.3"
itertools = "0.10.3"
vec1 = "1.6"
proptest = "1.0.0"

# Local deps
readyset-util = { path = "../readyset-util" }
mysql-time = { path = "../mysql-time" }
nom-sql = { path = "../nom-sql" }
readyset-data = { path = "../readyset-data" }
readyset-errors = { path = "../readyset-errors" }
partial-map = { path = "../partial-map" }

[dev-dependencies]
test-strategy = "0.2.0"
tokio = { workspace = true, features = ["full"] }
tokio-postgres = { workspace = true, features = ["with-chrono-0_4", "with-eui48-1", "with-uuid-0_8", "with-serde_json-1", "with-bit-vec-0_6"] }
mysql_async = { workspace = true }
